/**
 * Dashboard Configuration — default configuration and factory.
 *
 * No hardcoded layouts. All widget definitions, layout definitions,
 * refresh policies, provider rules, and permission rules are configurable.
 */
import type {
  DashboardConfiguration,
  WidgetDefinition,
  LayoutDefinition,
} from './types';

export const DEFAULT_WIDGET_DEFINITIONS: WidgetDefinition[] = [
  {
    type: 'health_score',
    title: 'Health Score',
    subtitle: 'Your PC health at a glance',
    category: 'health',
    priority: 'critical',
    size: 'medium',
    refreshPolicy: 'on_startup',
    providerName: 'HealthProvider',
    requiredCapabilities: [],
    permissions: { minPlan: 'FREE', requiredFeatures: [], requiresQuota: false, futurePolicies: {} },
    futureMetadata: {},
  },
  {
    type: 'overall_status',
    title: 'Overall Status',
    subtitle: 'Complete system overview',
    category: 'health',
    priority: 'high',
    size: 'medium',
    refreshPolicy: 'on_startup',
    providerName: 'HealthProvider',
    requiredCapabilities: [],
    permissions: { minPlan: 'FREE', requiredFeatures: [], requiresQuota: false, futurePolicies: {} },
    futureMetadata: {},
  },
  {
    type: 'ai_morning_brief',
    title: 'AI Morning Brief',
    subtitle: 'Your daily AI-powered summary',
    category: 'insights',
    priority: 'high',
    size: 'large',
    refreshPolicy: 'on_startup',
    providerName: 'InsightProvider',
    requiredCapabilities: ['ai_insights'],
    permissions: { minPlan: 'FREE', requiredFeatures: ['ai_insights'], requiresQuota: true, futurePolicies: {} },
    futureMetadata: {},
  },
  {
    type: 'top_recommendations',
    title: 'Top Recommendations',
    subtitle: 'Priority actions for your PC',
    category: 'recommendations',
    priority: 'high',
    size: 'large',
    refreshPolicy: 'on_demand',
    providerName: 'RecommendationProvider',
    requiredCapabilities: ['ai_recommendations'],
    permissions: { minPlan: 'FREE', requiredFeatures: ['ai_recommendations'], requiresQuota: true, futurePolicies: {} },
    futureMetadata: {},
  },
  {
    type: 'quick_wins',
    title: 'Quick Wins',
    subtitle: 'Fast improvements you can make now',
    category: 'recommendations',
    priority: 'medium',
    size: 'medium',
    refreshPolicy: 'on_demand',
    providerName: 'RecommendationProvider',
    requiredCapabilities: ['ai_recommendations'],
    permissions: { minPlan: 'FREE', requiredFeatures: ['ai_recommendations'], requiresQuota: true, futurePolicies: {} },
    futureMetadata: {},
  },
  {
    type: 'prediction_summary',
    title: 'Prediction Summary',
    subtitle: 'AI forecasts for your system',
    category: 'predictions',
    priority: 'medium',
    size: 'medium',
    refreshPolicy: 'scheduled',
    providerName: 'PredictionProvider',
    requiredCapabilities: ['ai_predictions'],
    permissions: { minPlan: 'FREE', requiredFeatures: ['ai_predictions'], requiresQuota: true, futurePolicies: {} },
    futureMetadata: {},
  },
  {
    type: 'recent_improvements',
    title: 'Recent Improvements',
    subtitle: 'Changes detected by AI',
    category: 'insights',
    priority: 'low',
    size: 'medium',
    refreshPolicy: 'on_startup',
    providerName: 'InsightProvider',
    requiredCapabilities: ['ai_insights'],
    permissions: { minPlan: 'FREE', requiredFeatures: ['ai_insights'], requiresQuota: true, futurePolicies: {} },
    futureMetadata: {},
  },
  {
    type: 'achievements',
    title: 'Achievements',
    subtitle: 'Badges and rewards earned',
    category: 'insights',
    priority: 'low',
    size: 'small',
    refreshPolicy: 'on_startup',
    providerName: 'AchievementProvider',
    requiredCapabilities: ['ai_insights'],
    permissions: { minPlan: 'FREE', requiredFeatures: ['ai_insights'], requiresQuota: false, futurePolicies: {} },
    futureMetadata: {},
  },
  {
    type: 'milestones',
    title: 'Milestones',
    subtitle: 'Progress towards your goals',
    category: 'insights',
    priority: 'low',
    size: 'small',
    refreshPolicy: 'on_startup',
    providerName: 'AchievementProvider',
    requiredCapabilities: ['ai_insights'],
    permissions: { minPlan: 'FREE', requiredFeatures: ['ai_insights'], requiresQuota: false, futurePolicies: {} },
    futureMetadata: {},
  },
  {
    type: 'optimization_history',
    title: 'Optimization History',
    subtitle: 'Past optimizations and results',
    category: 'history',
    priority: 'low',
    size: 'medium',
    refreshPolicy: 'on_startup',
    providerName: 'HistoryProvider',
    requiredCapabilities: [],
    permissions: { minPlan: 'FREE', requiredFeatures: [], requiresQuota: false, futurePolicies: {} },
    futureMetadata: {},
  },
  {
    type: 'storage_summary',
    title: 'Storage Summary',
    subtitle: 'Disk usage and capacity',
    category: 'system',
    priority: 'medium',
    size: 'medium',
    refreshPolicy: 'on_startup',
    providerName: 'HealthProvider',
    requiredCapabilities: [],
    permissions: { minPlan: 'FREE', requiredFeatures: [], requiresQuota: false, futurePolicies: {} },
    futureMetadata: {},
  },
  {
    type: 'performance_summary',
    title: 'Performance Summary',
    subtitle: 'CPU, RAM, and disk performance',
    category: 'system',
    priority: 'medium',
    size: 'medium',
    refreshPolicy: 'on_startup',
    providerName: 'HealthProvider',
    requiredCapabilities: [],
    permissions: { minPlan: 'FREE', requiredFeatures: [], requiresQuota: false, futurePolicies: {} },
    futureMetadata: {},
  },
  {
    type: 'privacy_summary',
    title: 'Privacy Summary',
    subtitle: 'Privacy and tracking protection',
    category: 'system',
    priority: 'low',
    size: 'small',
    refreshPolicy: 'on_startup',
    providerName: 'HealthProvider',
    requiredCapabilities: [],
    permissions: { minPlan: 'FREE', requiredFeatures: [], requiresQuota: false, futurePolicies: {} },
    futureMetadata: {},
  },
  {
    type: 'startup_summary',
    title: 'Startup Summary',
    subtitle: 'Startup items and boot time',
    category: 'system',
    priority: 'low',
    size: 'small',
    refreshPolicy: 'on_startup',
    providerName: 'HealthProvider',
    requiredCapabilities: [],
    permissions: { minPlan: 'FREE', requiredFeatures: [], requiresQuota: false, futurePolicies: {} },
    futureMetadata: {},
  },
  {
    type: 'windows_summary',
    title: 'Windows Summary',
    subtitle: 'Windows updates and services',
    category: 'system',
    priority: 'low',
    size: 'small',
    refreshPolicy: 'on_startup',
    providerName: 'HealthProvider',
    requiredCapabilities: [],
    permissions: { minPlan: 'FREE', requiredFeatures: [], requiresQuota: false, futurePolicies: {} },
    futureMetadata: {},
  },
  {
    type: 'device_profile',
    title: 'Device Profile',
    subtitle: 'AI-classified device type and workload',
    category: 'profile',
    priority: 'low',
    size: 'medium',
    refreshPolicy: 'on_startup',
    providerName: 'ProfileProvider',
    requiredCapabilities: ['ai_device_profile'],
    permissions: { minPlan: 'FREE', requiredFeatures: ['ai_device_profile'], requiresQuota: false, futurePolicies: {} },
    futureMetadata: {},
  },
  {
    type: 'subscription_status',
    title: 'Subscription Status',
    subtitle: 'Your current plan and features',
    category: 'subscription',
    priority: 'low',
    size: 'small',
    refreshPolicy: 'on_startup',
    providerName: 'CapabilityProvider',
    requiredCapabilities: [],
    permissions: { minPlan: 'FREE', requiredFeatures: [], requiresQuota: false, futurePolicies: {} },
    futureMetadata: {},
  },
  {
    type: 'usage_quotas',
    title: 'Usage Quotas',
    subtitle: 'AI quota usage and limits',
    category: 'subscription',
    priority: 'low',
    size: 'small',
    refreshPolicy: 'on_startup',
    providerName: 'QuotaProvider',
    requiredCapabilities: [],
    permissions: { minPlan: 'FREE', requiredFeatures: [], requiresQuota: false, futurePolicies: {} },
    futureMetadata: {},
  },
];

export const DEFAULT_LAYOUT_DEFINITIONS: LayoutDefinition[] = [
  {
    type: 'default',
    label: 'Default Layout',
    description: 'Balanced view for most users',
    widgetOrder: ['health_score', 'overall_status', 'ai_morning_brief', 'top_recommendations', 'quick_wins', 'prediction_summary', 'storage_summary', 'performance_summary', 'device_profile', 'optimization_history'],
    columns: 3,
    maxWidgets: 10,
    futureMetadata: {},
  },
  {
    type: 'compact',
    label: 'Compact Layout',
    description: 'Minimal view with key widgets only',
    widgetOrder: ['health_score', 'top_recommendations', 'storage_summary'],
    columns: 2,
    maxWidgets: 5,
    futureMetadata: {},
  },
  {
    type: 'detailed',
    label: 'Detailed Layout',
    description: 'Comprehensive view with all widgets',
    widgetOrder: ['health_score', 'overall_status', 'ai_morning_brief', 'top_recommendations', 'quick_wins', 'prediction_summary', 'recent_improvements', 'achievements', 'milestones', 'optimization_history', 'storage_summary', 'performance_summary', 'privacy_summary', 'startup_summary', 'windows_summary', 'device_profile', 'subscription_status', 'usage_quotas'],
    columns: 4,
    maxWidgets: 18,
    futureMetadata: {},
  },
  {
    type: 'beginner',
    label: 'Beginner Layout',
    description: 'Simple view for new users',
    widgetOrder: ['health_score', 'overall_status', 'ai_morning_brief', 'top_recommendations', 'optimization_history'],
    columns: 2,
    maxWidgets: 6,
    futureMetadata: {},
  },
  {
    type: 'advanced',
    label: 'Advanced Layout',
    description: 'Technical view for power users',
    widgetOrder: ['health_score', 'overall_status', 'top_recommendations', 'quick_wins', 'prediction_summary', 'performance_summary', 'startup_summary', 'windows_summary', 'device_profile', 'usage_quotas'],
    columns: 4,
    maxWidgets: 12,
    futureMetadata: {},
  },
  {
    type: 'custom',
    label: 'Custom Layout',
    description: 'User-customizable layout',
    widgetOrder: ['health_score', 'top_recommendations'],
    columns: 3,
    maxWidgets: 10,
    futureMetadata: {},
  },
];

export const DEFAULT_DASHBOARD_CONFIG: DashboardConfiguration = {
  dashboardVersion: '1.0.0',
  widgetDefinitions: [...DEFAULT_WIDGET_DEFINITIONS],
  layoutDefinitions: [...DEFAULT_LAYOUT_DEFINITIONS],
  defaultLayout: 'default',
  refreshRules: {
    realTimeIntervalMs: 5000,
    scheduledIntervalMs: 60000,
    backgroundIntervalMs: 30000,
    maxRetries: 3,
    retryDelayMs: 1000,
    parallelLoading: true,
  },
  permissionRules: {
    defaultMinPlan: 'FREE',
    strictMode: false,
    hideUnavailableWidgets: false,
    futureEnterprisePolicies: {},
  },
  providerRules: {
    timeoutMs: 5000,
    failOnError: false,
    cacheResults: true,
    cacheTtlMs: 10000,
  },
  featureFlags: {
    enableMorningBrief: true,
    enablePredictions: true,
    enableDeviceProfile: true,
    enableAchievements: true,
    enableMilestones: true,
    enableQuickWins: true,
    futureFlags: {},
  },
  maxWidgets: 20,
  enableEvents: true,
};

export type DeepPartial<T> = {
  [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P];
};

export function createDashboardConfig(
  overrides?: DeepPartial<DashboardConfiguration>,
): DashboardConfiguration {
  if (!overrides) return { ...DEFAULT_DASHBOARD_CONFIG };
  return {
    ...DEFAULT_DASHBOARD_CONFIG,
    ...overrides,
    widgetDefinitions: overrides.widgetDefinitions
      ? (overrides.widgetDefinitions as WidgetDefinition[])
      : DEFAULT_DASHBOARD_CONFIG.widgetDefinitions,
    layoutDefinitions: overrides.layoutDefinitions
      ? (overrides.layoutDefinitions as LayoutDefinition[])
      : DEFAULT_DASHBOARD_CONFIG.layoutDefinitions,
    refreshRules: { ...DEFAULT_DASHBOARD_CONFIG.refreshRules, ...overrides.refreshRules },
    permissionRules: { ...DEFAULT_DASHBOARD_CONFIG.permissionRules, ...overrides.permissionRules },
    providerRules: { ...DEFAULT_DASHBOARD_CONFIG.providerRules, ...overrides.providerRules },
    featureFlags: {
      ...DEFAULT_DASHBOARD_CONFIG.featureFlags,
      ...overrides.featureFlags,
      futureFlags: overrides.featureFlags?.futureFlags
        ? (overrides.featureFlags.futureFlags as Record<string, boolean>)
        : DEFAULT_DASHBOARD_CONFIG.featureFlags.futureFlags,
    } as typeof DEFAULT_DASHBOARD_CONFIG.featureFlags,
  };
}
