/**
 * Default Quota Definitions — built-in quota definitions for all
 * supported quota types.
 *
 * These are the default definitions that ship with the engine.
 * They can be overridden by loading a custom configuration.
 *
 * Adding new quota types only requires updating this file
 * (or providing a new configuration).
 */
import type { QuotaDefinition, QuotaConfig } from './types';

export const DEFAULT_QUOTAS: QuotaDefinition[] = [
  {
    id: 'ai_conversations',
    displayName: 'AI Conversations',
    description: 'Number of AI Assistant conversations per period',
    category: 'ai',
    enabled: true,
    limitType: 'count',
    limitValue: 5,
    resetPolicy: 'daily',
    usageUnit: 'count',
    isUnlimited: false,
  },
  {
    id: 'cleanup_size_mb',
    displayName: 'Cleanup Size',
    description: 'Total cleanup size in MB per period',
    category: 'cleanup',
    enabled: true,
    limitType: 'size_mb',
    limitValue: 500,
    resetPolicy: 'daily',
    usageUnit: 'mb',
    isUnlimited: false,
  },
  {
    id: 'files_cleaned',
    displayName: 'Files Cleaned',
    description: 'Number of files cleaned per period',
    category: 'cleanup',
    enabled: true,
    limitType: 'count',
    limitValue: 1000,
    resetPolicy: 'daily',
    usageUnit: 'files',
    isUnlimited: false,
  },
  {
    id: 'duplicate_removals',
    displayName: 'Duplicate Removals',
    description: 'Number of duplicate files removed per period',
    category: 'cleanup',
    enabled: true,
    limitType: 'count',
    limitValue: 50,
    resetPolicy: 'daily',
    usageUnit: 'files',
    isUnlimited: false,
  },
  {
    id: 'startup_changes',
    displayName: 'Startup Changes',
    description: 'Number of startup application changes per period',
    category: 'optimization',
    enabled: true,
    limitType: 'count',
    limitValue: 10,
    resetPolicy: 'daily',
    usageUnit: 'actions',
    isUnlimited: false,
  },
  {
    id: 'browser_cleanup_actions',
    displayName: 'Browser Cleanup Actions',
    description: 'Number of browser cleanup actions per period',
    category: 'privacy',
    enabled: true,
    limitType: 'count',
    limitValue: 5,
    resetPolicy: 'daily',
    usageUnit: 'actions',
    isUnlimited: false,
  },
  {
    id: 'optimization_runs',
    displayName: 'Optimization Runs',
    description: 'Number of optimization runs per period',
    category: 'optimization',
    enabled: true,
    limitType: 'count',
    limitValue: 3,
    resetPolicy: 'daily',
    usageUnit: 'count',
    isUnlimited: false,
  },
  {
    id: 'smart_optimize_runs',
    displayName: 'Smart Optimize Runs',
    description: 'Number of Smart Optimize runs per period',
    category: 'optimization',
    enabled: true,
    limitType: 'count',
    limitValue: 3,
    resetPolicy: 'daily',
    usageUnit: 'count',
    isUnlimited: false,
  },
  {
    id: 'report_exports',
    displayName: 'Report Exports',
    description: 'Number of report exports per period',
    category: 'reporting',
    enabled: true,
    limitType: 'count',
    limitValue: 10,
    resetPolicy: 'daily',
    usageUnit: 'exports',
    isUnlimited: false,
  },
  {
    id: 'pdf_exports',
    displayName: 'PDF Exports',
    description: 'Number of PDF exports per period',
    category: 'reporting',
    enabled: true,
    limitType: 'count',
    limitValue: 5,
    resetPolicy: 'daily',
    usageUnit: 'exports',
    isUnlimited: false,
  },
  {
    id: 'csv_exports',
    displayName: 'CSV Exports',
    description: 'Number of CSV exports per period',
    category: 'reporting',
    enabled: true,
    limitType: 'count',
    limitValue: 10,
    resetPolicy: 'daily',
    usageUnit: 'exports',
    isUnlimited: false,
  },
  {
    id: 'automation_executions',
    displayName: 'Automation Executions',
    description: 'Number of automation executions per period',
    category: 'automation',
    enabled: true,
    limitType: 'count',
    limitValue: 5,
    resetPolicy: 'daily',
    usageUnit: 'count',
    isUnlimited: false,
  },
  {
    id: 'cloud_syncs',
    displayName: 'Cloud Synchronizations',
    description: 'Number of cloud sync operations per period',
    category: 'cloud',
    enabled: true,
    limitType: 'count',
    limitValue: 10,
    resetPolicy: 'daily',
    usageUnit: 'count',
    isUnlimited: false,
  },
  {
    id: 'trend_history_access',
    displayName: 'Trend History Access',
    description: 'Number of trend history accesses per period',
    category: 'analytics',
    enabled: true,
    limitType: 'count',
    limitValue: 20,
    resetPolicy: 'daily',
    usageUnit: 'count',
    isUnlimited: false,
  },
];

export const DEFAULT_QUOTA_CONFIG: QuotaConfig = {
  quotas: DEFAULT_QUOTAS,
};
